### ISSUE TITLE
Account can be opened using same usernames

### ISSUE THREAD

**Issue by Gargi2906** [mayukh1998/DKB-GRS#1]
Multiple users with same usernames can open the account. This issue needs to be resolved.

**Comment by kush2404** [comment]
Fixed the issue. Check Release 0.2
![Screenshot_2020-06-14-18-46-31-022_com miui gallery](https://user-images.githubusercontent.com/64648097/84594422-b8029000-ae6f-11ea-94bd-2f3d6bbc6303.jpg)

**Comment by kush2404** [comment]
Fixed the issue. Check Release 0.2
![screenshot-dkbgrs-herokuapp-com-userregister-jsp-1592139359224](https://user-images.githubusercontent.com/64648097/84594970-1bda8800-ae73-11ea-8617-65daf40d4217.png)

**Comment by kush2404** [comment]
Fixed the issue
![screenshot-dkbgrs-herokuapp-com-userregister-jsp-1592139359224](https://user-images.githubusercontent.com/64648097/84595079-ade29080-ae73-11ea-9ee1-1bd3457d3eca.png)

**Comment by kush2404** [comment]
Check Release 0.2

**Comment by Gargi2906** [comment]
Issue is resolved.
