### ISSUE TITLE
Phone Number restrictions

### ISSUE THREAD

**Issue by Gargi2906** [mayukh1998/DKB-GRS#2]
Phone number field is taking more than 10 numbers. This issue also needs to be resolved.

**Comment by mayukh1998** [comment]
Phone Number Restrictions added. Now Cant provide more than 10 digits.
Fixed in Release 0.2


![screenshot-dkbgrs-herokuapp-com-userregister-jsp-1592139541297](https://user-images.githubusercontent.com/44093545/84593996-f9457080-ae6c-11ea-8ee2-a7e48cd1b62b.png)

**Comment by Gargi2906** [comment]
The issue is resolved.
