### ISSUE TITLE
Location column is not getting sorted in Assign and Monitor Issue page 

### ISSUE THREAD

**Issue by Gargi2906** [mayukh1998/DKB-GRS#3]
The location column of Assign issue and Monitor page is suppose to get sorted in ascending order. However, the same is not happening. This issue needs to get resolved.

**Comment by Aayush6196** [comment]
Sorting in location column fixed.

**Comment by Aayush6196** [comment]
Fixed in release 0.2

**Comment by Gargi2906** [comment]
Issue Resolved.
